// lib/generateReceipt.ts
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { formatUGX } from '../constants/theme';

interface ReceiptOptions {
  title: string; // e.g. "Payslip" or "Invoice"
  reference: string;
  date: string;
  partyLeft: { label: string; name: string; sub?: string };
  partyRight: { label: string; name: string; sub?: string };
  lineItems: { description: string; amount: number }[];
  total: { label: string; amount: number };
  footer?: string;
}

function buildHtml(opts: ReceiptOptions): string {
  const rows = opts.lineItems
    .map(
      (li) => `<tr><td style="padding:10px 0;border-bottom:1px solid #e5e7eb;">${li.description}</td>
      <td style="padding:10px 0;border-bottom:1px solid #e5e7eb;text-align:right;">${formatUGX(li.amount)}</td></tr>`
    )
    .join('');

  return `
  <html><head><meta charset="utf-8" />
  <style>
    body { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #111827; padding: 40px; }
    .header { display:flex; justify-content:space-between; border-bottom:2px solid #111827; padding-bottom:24px; margin-bottom:24px; }
    .brand { font-size:24px; font-weight:800; }
    .sub { font-size:13px; color:#6b7280; }
    .parties { display:flex; justify-content:space-between; margin-bottom:32px; }
    .party-label { font-size:12px; color:#6b7280; margin-bottom:4px; }
    .party-name { font-size:14px; font-weight:700; }
    table { width:100%; border-collapse:collapse; font-size:14px; }
    .total-row td { padding-top:16px; font-weight:800; font-size:16px; }
    .footer { margin-top:40px; padding-top:20px; border-top:1px solid #e5e7eb; font-size:11px; color:#9ca3af; text-align:center; }
  </style></head>
  <body>
    <div class="header">
      <div><div class="brand">WorkConnect</div><div class="sub">${opts.title}</div></div>
      <div style="text-align:right"><div class="sub">Ref: ${opts.reference}</div><div class="sub">${opts.date}</div></div>
    </div>
    <div class="parties">
      <div><div class="party-label">${opts.partyLeft.label}</div><div class="party-name">${opts.partyLeft.name}</div>${opts.partyLeft.sub ? `<div class="sub">${opts.partyLeft.sub}</div>` : ''}</div>
      <div style="text-align:right"><div class="party-label">${opts.partyRight.label}</div><div class="party-name">${opts.partyRight.name}</div>${opts.partyRight.sub ? `<div class="sub">${opts.partyRight.sub}</div>` : ''}</div>
    </div>
    <table>
      <thead><tr><th style="text-align:left;padding-bottom:8px;border-bottom:2px solid #111827;">Description</th><th style="text-align:right;padding-bottom:8px;border-bottom:2px solid #111827;">Amount</th></tr></thead>
      <tbody>${rows}
        <tr class="total-row"><td>${opts.total.label}</td><td style="text-align:right">${formatUGX(opts.total.amount)}</td></tr>
      </tbody>
    </table>
    <div class="footer">${opts.footer || 'Generated by WorkConnect — this is a system-generated document and does not require a signature.'}</div>
  </body></html>`;
}

/** Generates a real PDF and opens the native share/save sheet — works for
 * both payslips and invoices with the same underlying template.
 *
 * Note: file-sharing via expo-sharing can behave differently inside plain
 * Expo Go versus a real EAS build — Expo Go's FileProvider is registered
 * under Expo Go's own package name, not your app's, which can cause
 * sharing to work less reliably there than in an actual built app. If
 * this fails specifically in Expo Go but not in a production/dev-client
 * build, that's the explanation — not a bug in this function. */
export async function generateAndShareReceipt(opts: ReceiptOptions): Promise<void> {
  const html = buildHtml(opts);
  const { uri } = await Print.printToFileAsync({ html });
  const canShare = await Sharing.isAvailableAsync();
  if (!canShare) {
    throw new Error('Sharing is not available on this device.');
  }
  try {
    await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: `${opts.title} ${opts.reference}` });
  } catch (err: any) {
    // Re-throw with the underlying native message intact so the caller's
    // toast shows something actionable instead of a bare rejection.
    throw new Error(err?.message || 'Failed to open the share sheet for this PDF.');
  }
}
